config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweets#index'
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'

  put 'users/follow/:user_id',to: 'users#follow'
  put 'users/unfollow/:user_id',to: 'users#unfollow'
  get 'users/follow_list/:user_id',to: 'users#follow_list'
  get 'users/follower_list/:user_id',to:'users#follower_list'
  get '/mypage' => 'users#mypage'

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :users do
    member do
     get :following, :followers
     end
  end
  
  resources :relationships, only: [:create, :destroy]
  
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
  
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord

    def change
        create_table :relationships do |t|
          t.integer :follower_id
          t.integer :following_id
    
          t.timestamps null: false
        end
    
        add_index :relationships, :follower_id
        add_index :relationships, :following_id
        add_index :relationships, [:follower_id, :following_id], unique: true
    end

    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true

end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord

    mount_uploader :image, ImageUploader
    mount_uploader :video, VideoUploader

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    
    belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :tweets, dependent: :destroy 
         has_many :likes, dependent: :destroy
         has_many :liked_tweets, through: :likes, source: :tweet
         has_many :comments, dependent: :destroy

         has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
         has_many :followings, through: :following_relationships
         has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
         has_many :followers, through: :follower_relationships

         def following?(other_user)
            following_relationships.find_by(following_id: other_user.id)
         end
        
         def follow!(other_user)
            following_relationships.create!(following_id: other_user.id)
         end
        
         def unfollow!(other_user)
            following_relationships.find_by(following_id: other_user.id).destroy
         end

         acts_as_followable 
         acts_as_follower

         def already_liked?(tweet)
            self.likes.exists?(tweet_id: tweet.id)
         end

         validates :name, presence: true 
         validates :profile, length: { maximum: 200 } 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!

    def create
      tweet = Tweet.find(params[:tweet_id])
      comment = tweet.comments.build(comment_params) 
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path)
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path)
    end

end

private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController

    def top
    end

    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) 
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

    def create
        @user = User.find(params[:relationship][:following_id])
        current_user.follow!(@user)
        redirect_to @user
    end
    
    def destroy
        @user = Relationship.find(params[:id]).following
        current_user.unfollow!(@user)
        redirect_to @user
    end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

    def index
      if params[:search] == nil
        @tweets= Tweet.all
      elsif params[:search] == ''
        @tweets= Tweet.all
      else
        @tweets = Tweet.where("body LIKE ? ",'%' + params[:search] + '%')
      end
    end

    def new
        @tweet = Tweet.new
    end

    def create
      tweet = Tweet.new(tweet_params)
      tweet.user_id = current_user.id

      if tweet.save
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
    end

    def show
      @tweet = Tweet.find(params[:id])
      @comments = @tweet.comments
      @comment = Comment.new
    end

    def destroy
      tweet = Tweet.find(params[:id])
      tweet.destroy
      redirect_to action: :index
    end
  
    private
    def tweet_params
      params.require(:tweet).permit(:body, :image)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id]) 
    end

    def following
        @user  = User.find(params[:id])
        @users = @user.followings
        render 'show_follow'
    end
  
    def followers
      @user  = User.find(params[:id])
      @users = @user.followers
      render 'show_follower'
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def current_user?(user)
        user == current_user
    end

end

app/views/tweets/create.js.erb
("#like-button-zone_<%= @receiving_user.id %>").html("<%= j(render partial: 'likes/like', locals: { user: @receiving_user }) %>");
(".like_balance").html("<%= @sending_user.like_balance %>")

app/views/tweets/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>


<div class="search-container">
    <h3>投稿を検索してみよう！</h3>
    <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
      <%= text_field_tag :search %>
      <%= submit_tag '検索する'  %>
    <% end %>
</div>

<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
        <div class="contents">
           <h3>ユーザー名:<%= t.user.name %></h3>
           <ul>
              <h4>ツイート<h4>
              <li><%= image_tag t.image_url, size: "250x200" if t.image? %>
              <li><%= t.body %><li>
              <p>
              <%= link_to t.video_url.to_s do %>
              <%= video_tag(t.video.to_s) %>
              <% end %>
              </p>
           </ul>
        </div>   

                <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                    <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                      <i class="fas fa-heart"></i><%= t.likes.count %>
                    <% end %>
                <% else %>
                    <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                        <i class="fas fa-heart"></i><%= t.likes.count %>  
                    <% end %>
                <% end %>
              <% else %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>

              <div class="right-container">
                <p class="time"><%= t.created_at %></p>
                <%= link_to "詳細へ", tweet_path(t.id) %>
                <%= button_to "削除する", tweet_path(t.id), method: :delete %>
              </div>
      </div>
  <% end %>
</div>


app/views/tweets/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>


<div class="tweet-in">
      <h2>ツイートを投稿しよう！！</h2>

    <%= form_for @tweet do |f| %>
  
  <div class="field">
    <%= f.text_field :body, :size => 140 %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :video %>
    <%= f.file_field :video, :accept => 'video/*' %>
  </div>
   
  <%= f.submit "ここから投稿する" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>


app/views/tweets/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>

<h1>ツイートの詳細</h1>

<div class="tweets-container">
    <div class="tweet">
        <div class="contents">
          <h2>ユーザー名:<%= @tweet.user.name %></h2>
          <ul>
            <h2>ツイート:<%= @tweet.body %></h2>
            <%= link_to @tweet.video_url.to_s do %>
            <%= video_tag(@tweet.video.to_s) %>
            <% end %>
          </ul>

        <% if user_signed_in? %>
            <% if current_user.already_liked?(@tweet) %>
              <%= link_to tweet_like_path(@tweet), method: :delete do %>
                  <i class="fas fa-heart"></i><%= @tweet.likes.count %>
              <% end %>
            <% else %>
              <%= link_to tweet_likes_path(@tweet), method: :post do %>
                  <i class="fas fa-heart"></i><%= @tweet.likes.count %>
              <% end %>
            <% end %>
        <% else %>
            <i class="far fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
     </div>

          <% @tweet.liked_users.each do |user| %>
            <li><%= user.email %></li>
          <% end %>

      <div class="comment-wrapper">
        <% @comments.each do |c| %>
          <div>
            <%= c.user.name unless c.user.blank? %>
            <br>
            <%= c.content %>
          </div>
            <br>
        <% end %>

        <% if user_signed_in? %>
          <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
            <%= f.text_area :content %>
            <%= button_tag type: "submit" do %>
              <i class="far fa-comments"></i> コメントする
            <% end %>
          <% end %>
        <% end %>
      </div>
      <p><%= @tweet.created_at %></p>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
    <div><%= f.hidden_field :following_id %></div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form">
<% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
<% else %>
  <%= render 'follow' %>
<% end %>
</div>
<% end %>  

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'usershow', :media => "all" %>

<h1>マイページ</h1>

<div class="profile">
    <p>名前 : <%= @user.name %></p>
    <p>メールアドレス : <%= @user.email %></p>
    <p>プロフィール : <%= @user.profile %></p>

    <%= render 'follow_form' %>
    <%= render 'stats' %>
</div>


<h2>あなたの投稿一覧</h2>

<div class="tweets-container">
    <% @user.tweets.each do |t| %>
      <div class="tweet">
        <div class="main-box">
        <div class="name-container"><%= t.user.email %></div>
            <div class="left-container">
              <%= image_tag t.image_url, size: "250x200" if t.image? %>
              <%= t.body %>
              <p>
              <%= link_to t.video_url.to_s do %>
              <%= video_tag(t.video.to_s) %>
              <% end %>
              </p>
              <p class="time"><%= t.created_at %></p>
            </div>  
        </div>
      </div>
        
    <% end %>
</div>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
    <table>
    <tr>
      <td>  <%= user.username %> </td>
      <td><%= link_to '詳細', user_path(user) %></td>
    </tr>
    
    </table>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
    <table>
    <tr>
      <td>  <%= user.username %> </td>
      <td><%= link_to '詳細', user_path(user) %></td>
    </tr>
    
    </table>
<% end %>